name: C/C++ CI

on: [push]

concurrency: 
  group: environment-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: apt
      run: |
        sudo apt update
        sudo apt install cpmtools flex bison libreadline-dev libz80ex-dev lua5.2
    - name: build-ack
      run: |
        git clone --depth=1 https://github.com/davidgiven/ack.git
        sed -i 's/PLATS = all/PLATS = cpm/' ack/Makefile
        make -C ack PREFIX=$HOME install
    - name: make
      run: PATH=$PATH:$HOME/bin make

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name:  ${{ github.event.repository.name }}.${{ github.sha }}
        path: |
          pn8510.img
          pn8800.img
          lw30.img
          wp2450.img
          wp1.img
          kayproii.img
          nc200.img
      