name: C/C++ CI

on: [push]

concurrency: 
  group: environment-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: apt
      run: |
        sudo apt update
        sudo apt install cpmtools bazel-bootstrap flex bison libreadline-dev libz80ex-dev lua5.2
    - name: build-ack
      run: |
        git clone --depth=1 https://github.com/davidgiven/ack.git
        make -C ack PREFIX=$HOME +ack-cpm
        make -C ack PREFIX=$HOME install
    - name: make
      run: PATH=$PATH:$HOME/bin make

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name:  ${{ github.event.repository.name }}.${{ github.sha }}
        path: |
          bazel-bin/arch/brother/pn8510/diskimage.img
          bazel-bin/arch/brother/pn8800/diskimage.img
          bazel-bin/arch/brotherop2/diskimage.img
          bazel-bin/arch/brotherwp1/diskimage.img
          bazel-bin/arch/kayproii/diskimage.img
          bazel-bin/arch/nc200/diskimage.img
          bazel-bin/arch/wp2450ds/diskimage.img
      